apiVersion: v1
kind: Service

metadata:
  name: jenkin-master-tunnel
  namespace: jenkins
spec:
  selector:
    app: master
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 50000
