kind: Service
apiVersion: v1
metadata:
  name: jenkins-load-balancer
spec:
  selector:
    app: master
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 182.73.220.114/32
  - 42.61.111.193/32
  - 133.237.7.78/32
  - 133.237.7.64/27
  - 133.237.44.32/27
